### ISSUE TITLE
'Cannot infer the type from the element' on integer element

### ISSUE THREAD

**Issue by benmaier** [gstonge/SamplableSet#34]
Here's a fun one. I'm trying to construct neighbor sampling sets from a network I generated using numpy. 

I initiate a set like so: 

```python
SamplableSet(1,1,neighbors,cpp_type='int')
```

where `neighbors` might look something like

```python
{480: 1.0, 479: 1.0, 476: 1.0}
```

I'm getting the error

```
Cannot infer the type from the element
```

Problem: I was generating edges from a node list that is a numpy array with type `numpy.in64`. And SamplableSet doesn't like that :)

# Solution

Converting element integers from  `numpy.in64` to Python native `int`.

Not sure if there needs to be something changed in this package. I just thought I open this issue so that people can find it when they encounter the same error. I'll close the issue right after posting, feel free to reopen it if it is indeed an issue.

**Comment by gstonge** [comment]
Good catch! In fact, inferring the type fails when using `numpy.int`, but once a samplable set of type `int` has been initialized, you can use `numpy.int` without trouble. I made sure that when both an iterable `elements_weights` and `cpp_type` are passed as argument, the later is used by default for the type. This way, your command
```python
SamplableSet(1,1,neighbors,cpp_type='int')
```
now works, even if `neighbors` uses `numpy.int`. This is fixed by the last commit.

**Comment by benmaier** [comment]
that's great, thank you!
